### ISSUE TITLE
Nicer pypi decription

### ISSUE THREAD

**Issue by andim** [bjodah/pyneqsys#30]
PyPI does not seem to render the restructured text markup (https://pypi.python.org/pypi/pyneqsys), which makes the description of the package there hard to read. You might want to clean up the text that is displayed on PyPI.

[This is a suggestion and you are free to disregard it.]

**Comment by bjodah** [comment]
I ran [rstcheck](https://pypi.python.org/pypi/rstcheck/0.5) and [rst-lint](https://pypi.python.org/pypi/restructuredtext_lint), and re-released v0.5 as v0.5.2 to push the new description to PyPI. It looks like it did the trick:
https://pypi.python.org/pypi/pyneqsys/0.5.2

Thanks for bringing it to my attention.
