### ISSUE TITLE
Adding DOIs to the references

### ISSUE THREAD

**Issue by andim** [bjodah/pyneqsys#33]
[This issue is part of the JOSS review, see openjournals/joss-reviews/issues/531.]

Could you please add DOIs to the references where not already done? At least for the sundials paper their appears to be one (10.1145/1089014.1089020) potentially also for some of the other references.

**Comment by bjodah** [comment]
Thanks for the SUNDIALS doi (I missed it the first time). For the other references I came up empty handed. However the NLEQ2 now has a "urn" identifier which [ZIB](https://opus4.kobv.de/opus4-zib/frontdoor/index/index/docId/485) asked that citing parties use.

**Comment by andim** [comment]
Sounds good. I don't want to send you hunting DOIs that don't exist, but you could add the one for Sundials. :+1:

**Comment by bjodah** [comment]
Thanks, I added it: https://github.com/bjodah/pyneqsys/blob/master/joss-paper/paper.bib#L15
