### ISSUE TITLE
Add short description of problem to be solved to examples

### ISSUE THREAD

**Issue by andim** [bjodah/pyneqsys#35]
[This issue is part of the JOSS review, see openjournals/joss-reviews#531.]

The examples are very good to document the functionality of the software and especially the notebooks are well-documented. For the pure python examples it would be great to have a short description of the problem to be solved as a comment in the file.

**Comment by bjodah** [comment]
Glad to hear you like what you saw in the notebooks.
The examples were, as you noted, very terse. I tried to address this in gh-36 as well, let me know what you think.

**Comment by andim** [comment]
Looks good!
